name: HNA Monnitoring and Logging Agent
description: |
  Monnitoring and Logging agent for HNA data center
version: v0.4
category: HNA
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
